finally
value error caught in outer
